Project Popup Window
samWfelice/Portfolio pull request #10
Opened 2022-05-18 15:25 UTC by samWfelice

- Created Temporary Popup with overlay background for mobile and desktop for reference to write javascript fucntion.
- Created a ``displayPopup()`` function which dynamically creates HTML when the user clicks on "See Project" Button
- Used loops to iterate through id's of button so that the content is specific to the project
- Finally, Event listeners are used to see user's interaction with the webpage and when the user click on the "See Project" Button it pop ups and when the user clicks or taps on the cross icon the HTML is deleted!

2022-05-18 16:40 UTC, codepantha requested changes
Hi team 👋,

## STATUS: REQUESTED CHANGES ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

### Highlights ⭐ 🎯 
✔️ Descriptive PR
✔️Meaningful commit messages
✔️ Linter checks
✔️ Professional README

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-18 16:40 UTC, codepantha commented on Js/app.js
> +  btnWrapper.appendChild(liveBtn);
The popup design doesn't follow the Figma design specs and cuts off some vital information.

- [ ] Please fix the 'See Live' and 'See Source' buttons not showing on both desktop and mobile devices🙏 
- [ ] Please increase the width of the popup to match the Figma design
### Your Design
![image](https://user-images.githubusercontent.com/46839548/169094773-e65adfa2-6ad1-4605-919b-ed7f69172018.png)

### Figma Design
![image](https://user-images.githubusercontent.com/46839548/169094026-d72ba952-4d50-4ee7-b97c-ee74c058854c.png)

2022-05-18 17:49 UTC, samWfelice commented on Js/app.js
> +  btnWrapper.appendChild(liveBtn);
Hello @codepantha !
The buttons are visible, can you please tell me if they are overflowing from the screen you're reviewing form or are they not visible at all? As I can check through the live link, the buttons are visible and working perfectly!

2022-05-18 21:43 UTC, codepantha commented on Js/app.js
> +  btnWrapper.appendChild(liveBtn);
Hi @samWfelice 👋 
They are neither visible on chrome nor firefox browsers

2022-05-19 06:41 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @samWfelice, and @Kirabo19👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-19 07:20 UTC, merged