Added Work Section & About Me Section
samWfelice/Portfolio pull request #2
Opened 2022-04-21 14:34 UTC by samWfelice

**Features I added to the project:**
- Work section show-casing my abilities
- About myself section describing myself, my Skills, Frameworks and Languages I use
- Use [this ](https://htmlpreview.github.io/?https://github.com/samWfelice/Portfolio/blob/work-about/index.html)live link

2022-04-21 17:33 UTC, Munsa1 requested changes
Hi @samWfelice , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Linters passing
- Descriptive pull request
- Professional readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 17:33 UTC, Munsa1 commented on README.md
>  - LinkedIn: [LinkedIn](https://www.linkedin.com/in/samfelice/)
Good job adding the links to your readme file.
- Kindly add the correct LinkedIn handle like you have done for the Github and Twitter handles, as this will make your readme file consistent with professional standards.

2022-04-21 17:33 UTC, Munsa1 commented on index.html
> +                </ul>
Great job implementing this section of the portfolio, however, if you look closely, the languages are not properly aligned in line with the Figma template, and your design is not starting from the `Languages` header.

- Figma Design
![image](https://user-images.githubusercontent.com/81932478/164513661-6f87e67a-47ca-4dfd-9bc8-9761a3aa5a90.png)

- Your Design
![image](https://user-images.githubusercontent.com/81932478/164513840-d883208c-8efd-4fae-95cf-ed759f19cd2c.png)

2022-04-21 17:33 UTC, Munsa1 commented on style.css
> +}
Your button looks good, however, you have not implemented the button: hover, button: pressed and button: active styles which are core requirements. Kindly do so to enhance your user accessibility.

Refer to the screenshot below
![image](https://user-images.githubusercontent.com/81932478/164516443-3d925f9f-af78-4a65-93ee-68d3438b40c5.png)

Or you can check the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

2022-04-22 05:02 UTC, gtekle approved these changes
Hi @samWfelice , 

## Approved

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![clapping-leonardo-dicaprio](https://user-images.githubusercontent.com/44057863/164606456-b29ed5ee-16a8-48eb-9b48-3c9d794d2d7b.gif)


## Highlights
:heavy_check_mark: Clean and well organized code
:heavy_check_mark: Implemented all requeseted changes by previous reviewer
:heavy_check_mark: Nice UI
:heavy_check_mark: Good use of GitHub flow

## Optional suggestions

- [ ] Please check the optional suggestion in the inline comments below and make sure to implement them before you merge this pull request.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 05:02 UTC, gtekle commented on README.md
- [ Optional ] You should add the `Getting Started` section as per the README [template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse. You can add things like: `how to clone the repo`, `how to run it locally`, `prerequisites`, etc under this section

2022-04-22 05:02 UTC, gtekle commented on index.html
> +            <h1 class="about-me-heading">About Myself</h1>
- [ Optional ] You should have only one `<h1>` tag used for the most important heading in your HTML document for semantic reasons such as Search Engine Optimization (SEO). So, kindly replace this `<h2>`

2022-04-22 05:02 UTC, gtekle commented on index.html
> +                <li><a href="#" class="icon-link"><img src="./images/icons/medium.svg" alt="Medium Logo"></a></li>
- [ Optional ] It is good to add proper links to your social media accounts in the `href` property of the `<a>` tags here. The social media icons represent `GitHub`, `LinkedIn`, `Angelist`, `twitter`, and `Medium`.

2022-04-22 08:51 UTC, merged