Navigation menu mobile
samWfelice/Portfolio pull request #9
Opened 2022-05-16 18:17 UTC by samWfelice

- Add HTML for Mobile Navigation Menu
- Styled it using CSS
- Used Javascript to open and close the Menu

2022-05-16 18:41 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please add your partner name and social links to readme file like you info in the image below.

![image](https://user-images.githubusercontent.com/68796232/168660918-735902ca-ad07-4da2-a007-c3d32408c30c.png) 

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-16 18:41 UTC, omar-muhamad commented on index.html
> +        </nav>
- [ ] Great job on the mobile menu but there is an issue in the desktop view which is the nave links now don't appear on the desktop view, So Please fix that.

![image](https://user-images.githubusercontent.com/68796232/168659267-0e097917-33c2-45f5-979d-b7fee09f2fde.png)

2022-05-16 18:41 UTC, omar-muhamad commented on Js/app.js
> +const secondClick = document.querySelector('.cross-icon');
- [ ] [Optional] [Highly recommended] It would be better professionally if you named the element by its name for this example you could `hamburgerBtn` or `navIcon` instead of `firstClick` and `closeBtn` or `crossIcon` instead of `seconedClick` to make your code more readable.

2022-05-16 18:41 UTC, omar-muhamad commented on style.css
> +  backdrop-filter: blur(4px);
- [ ] Nice work here using `backdrop-filter` 👍.

2022-05-17 05:34 UTC, Ismailco approved these changes
### Hi @samWfelice,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-17 05:59 UTC, merged